# Binance Stop Loss Manager Configuration

# API Configuration
api:
  rate_limit_calls_per_second: 10
  max_retries: 3
  retry_delay: 1

# Monitoring Configuration
monitoring:
  normal_interval: 30  # seconds
  aggressive_interval: 10  # seconds when in profit
  retry_interval: 60  # seconds for error retry
  health_check_interval: 300  # seconds

# Stop Loss Configuration
stop_loss:
  atr_period: 14
  atr_multiplier: 1.5
  risk_percentage: 0.02  # 2% risk per trade
  trailing_stop_percentage: 0.001  # 0.1% trailing stop
  min_stop_distance: 0.005  # 0.5% minimum distance
  taker_fee_rate: 0.0005  # 0.05% taker fee (configurable)
  timeframe: '15m'  # Timeframe for indicator calculation (e.g. 15m, 1h, 4h)
  min_net_profit_to_move_sl: 0.0005  # 0.05% threshold for moving SL
  breakeven_buffer: 0.001  # 0.1% buffer above breakeven point

# Caching Configuration
cache:
  position_cache_ttl: 30  # seconds
  price_cache_ttl: 5  # seconds
  atr_cache_ttl: 300  # seconds

# Logging Configuration
logging:
  level: INFO
  max_bytes: 5242880  # 5MB (5 * 1024 * 1024 bytes)
  backup_count: 3     # Keep 3 backup files
  format: "%(asctime)s - %(levelname)s - %(message)s"

# Trading Configuration
trading:
  max_positions: 10
  min_position_size: 0.001
  enable_trailing_stop: true
  enable_atr_stop: true
  enable_percentage_stop: true 