version: '3.8'

services:
  stop-loss-manager:
    build: .
    container_name: binance-stop-loss-manager
    volumes:
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml:ro
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Bangkok
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
